# ETL 01 - Scripts DDL SQL Server Express
    Objetivo: Criação do bancos de dados DSTG_OiMasterDados
              Criação do bancos de dados DDTM_OiMasterDados
              Criação dos esquemas OiMasterDados nos bancos criados
              Criação das tabelas no banco DSTG_OiMasterDados
              Criação das tabelas no banco DDTM_OiMasterDados
    Desenvolvedor: Marcelo Muniz de Alencar

In [2]:
import os # pacote para sistema operacional
import pyodbc # pacote manipulação de bancos de dados
import pandas as pd  # pacote pandas

import warnings
warnings.filterwarnings("ignore")

In [ ]:
# criar o diretório para arquivo de dados
if not os.path.exists('C:/MSSQL/Data'):
    os.makedirs('C:/MSSQL/Data')
    
# criar o diretório para arquivo de log
if not os.path.exists('C:/MSSQL/Log'):
    os.makedirs('C:/MSSQL/Log')

In [ ]:
# conexão banco de dados 'master' no servidor
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=PCMARCELO\SQLEXPRESS;' # alterar linha para seu servidor
                      'Database=master;'
                      'Trusted_Connection=yes;',autocommit=True)

In [ ]:
# criando banco de dados DSTG_OiMasterDados
cursorDSTG = conn.cursor()

sqlDSTG_OiMasterDados = ''' 
CREATE DATABASE [DSTG_OiMasterDados]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DSTG_OiMasterDados', FILENAME = N'C:\MSSQL\Data\DSTG_OiMasterDados.mdf' , SIZE = 466944KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DSTG_OiMasterDados_log', FILENAME = N'C:\MSSQL\Log\DSTG_OiMasterDados_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DSTG_OiMasterDados].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [DSTG_OiMasterDados] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET ANSI_NULLS OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET ANSI_PADDING OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET ANSI_WARNINGS OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET ARITHABORT OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET AUTO_CLOSE OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET AUTO_SHRINK OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [DSTG_OiMasterDados] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [DSTG999] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET  DISABLE_BROKER 

ALTER DATABASE [DSTG_OiMasterDados] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET TRUSTWORTHY OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [DSTG_OiMasterDados] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [DSTG999] SET RECOVERY SIMPLE 

ALTER DATABASE [DSTG_OiMasterDados] SET  MULTI_USER 

ALTER DATABASE [DSTG_OiMasterDados] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [DSTG_OiMasterDados] SET DB_CHAINING OFF 

ALTER DATABASE [DSTG_OiMasterDados] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [DSTG_OiMasterDados] SET TARGET_RECOVERY_TIME = 60 SECONDS 

ALTER DATABASE [DSTG_OiMasterDados] SET DELAYED_DURABILITY = DISABLED 

ALTER DATABASE [DSTG_OiMasterDados] SET ACCELERATED_DATABASE_RECOVERY = OFF  

ALTER DATABASE [DSTG_OiMasterDados] SET QUERY_STORE = OFF

ALTER DATABASE [DSTG_OiMasterDados] SET  READ_WRITE 
 '''

# Verificar se os bancos de dados DSTG_OiMasterDados já existe
sqlDSTG = """
SELECT *
FROM master.sys.databases
WHERE name = 'DSTG_OiMasterDados'
""" 
dfDSTG = pd.read_sql(sqlDSTG, conn)

try:
    if dfDSTG.empty:
        cursorDSTG.execute(sqlDSTG_OiMasterDados)
        conn.commit()
        print('Banco DSTG_OiMasterDados criado.')
    else:
        print('Banco DSTG_OiMasterDados já existe.')
except:
    print('Erro. Contactar desenvolvedor!')

In [ ]:
# criando banco de dados DDTM_OiMasterDados
cursorDDTM = conn.cursor()

sqlDDTM_OiMasterDados = ''' 
CREATE DATABASE [DDTM_OiMasterDados]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DDTM_OiMasterDados', FILENAME = N'C:\MSSQL\Data\DDTM_OiMasterDados.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DDTM_OiMasterDados_log', FILENAME = N'C:\MSSQL\Log\DDTM_OiMasterDados_log.ldf' , SIZE = 1777664KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DDTM_OiMasterDados].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [DDTM_OiMasterDados] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET ANSI_NULLS OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET ANSI_PADDING OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET ANSI_WARNINGS OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET ARITHABORT OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET AUTO_CLOSE OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET AUTO_SHRINK OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [DDTM_OiMasterDados] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [DDTM_OiMasterDados] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET  DISABLE_BROKER 

ALTER DATABASE [DDTM_OiMasterDados] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET TRUSTWORTHY OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [DDTM999] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET RECOVERY SIMPLE 

ALTER DATABASE [DDTM_OiMasterDados] SET  MULTI_USER 

ALTER DATABASE [DDTM_OiMasterDados] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [DDTM_OiMasterDados] SET DB_CHAINING OFF 

ALTER DATABASE [DDTM_OiMasterDados] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [DDTM_OiMasterDados] SET TARGET_RECOVERY_TIME = 60 SECONDS 

ALTER DATABASE [DDTM_OiMasterDados] SET DELAYED_DURABILITY = DISABLED 

ALTER DATABASE [DDTM_OiMasterDados] SET ACCELERATED_DATABASE_RECOVERY = OFF  

ALTER DATABASE [DDTM_OiMasterDados] SET QUERY_STORE = OFF

ALTER DATABASE [DDTM_OiMasterDados] SET  READ_WRITE 
 '''

# Verificar se os bancos de dados DDTM_OiMasterDados já existe
sqlDDTM = """
SELECT *
FROM master.sys.databases
WHERE name = 'DDTM_OiMasterDados'
""" 
dfDDTM = pd.read_sql(sqlDDTM, conn)

try:
    if dfDDTM.empty:
        cursorDDTM.execute(sqlDDTM_OiMasterDados)
        conn.commit()
        print('Banco DDTM_OiMasterDados criado.')
    else:
        print('Banco DDTM_OiMasterDados já existe.')
except:
    print('Erro. Contactar desenvolvedor!')

In [3]:
# conexão banco de dados 'DSTG_OiMasterDados' no servidor
connDSTG = pyodbc.connect('Driver={SQL Server};'
                      'Server=PCMARCELO\SQLEXPRESS;' # alterar linha para seu servidor
                      'Database=DSTG_OiMasterDados;'
                      'Trusted_Connection=yes;',autocommit=True)

# conexão banco de dados 'DDTM_OiMasterDados' no servidor
connDDTM = pyodbc.connect('Driver={SQL Server};'
                      'Server=PCMARCELO\SQLEXPRESS;' # alterar linha para seu servidor
                      'Database=DDTM_OiMasterDados;'
                      'Trusted_Connection=yes;',autocommit=True)

In [ ]:
# criando esquemas OiMasterDados para os banco de dados DSTG_OiMasterDados
cursorDSTG_Schema = connDSTG.cursor()

sqlDSTG_OiMasterDados_Schema = ''' use DSTG_OiMasterDados
                                    IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'jim')
                                        BEGIN
                                            EXEC('CREATE SCHEMA OiMasterDados')
                                        END '''

try:
    cursorDSTG_Schema.execute(sqlDSTG_OiMasterDados_Schema)
    connDSTG.commit()
    print('Executado o script SQL para criação do esquema no DSTG.')
except:
    print('Erro. Contactar desenvolvedor!')

In [ ]:
# criando esquemas OiMasterDados para os banco de dados DDTM_OiMasterDados
cursorDDTM_Schema = connDDTM.cursor()

sqlDDTM_OiMasterDados_Schema = ''' use DDTM_OiMasterDados
                                    IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'OiMasterDados')
                                        BEGIN
                                            EXEC('CREATE SCHEMA OiMasterDados')
                                        END '''

try:
    cursorDDTM_Schema.execute(sqlDDTM_OiMasterDados_Schema)
    connDDTM.commit()
    print('Executado o script SQL para criação do esquema no DDTM.')
except:
    print('Erro. Contactar desenvolvedor!')

In [4]:
# conexão banco de dados 'DSTG_OiMasterDados' no servidor
connDSTG = pyodbc.connect('Driver={SQL Server};'
                      'Server=PCMARCELO\SQLEXPRESS;' # alterar linha para seu servidor
                      'Database=DSTG_OiMasterDados;'
                      'Trusted_Connection=yes;',autocommit=True)

# conexão banco de dados 'DDTM_OiMasterDados' no servidor
connDDTM = pyodbc.connect('Driver={SQL Server};'
                      'Server=PCMARCELO\SQLEXPRESS;' # alterar linha para seu servidor
                      'Database=DDTM_OiMasterDados;'
                      'Trusted_Connection=yes;',autocommit=True)

In [7]:
# criando as tabelas no esquema OiMasterDados para os banco de dados DSTG_OiMasterDados
cursorDSTG_Tabela = connDSTG.cursor()

sqlDSTG_OiMasterDados_Tab01 = ''' 
use DSTG_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiSTG_Calendario')   
       DROP TABLE [OiMasterDados].[TOiSTG_Calendario]
   
CREATE TABLE [OiMasterDados].[TOiSTG_Calendario](
	[NumData] [varchar](255) NULL,
	[DescData] [varchar](255) NULL,
	[NumAno] [int] NULL,
	[DescAno] [varchar](255) NULL,
	[NumSemestre] [int] NULL,
	[DescSemestre] [varchar](255) NULL,
	[NumTrimestre] [int] NULL,
	[DescTrimestre] [varchar](255) NULL,
	[NumMes] [int] NULL,
	[DescMes] [varchar](255) NULL,
	[NumSemanaAno] [int] NULL,
	[DescSemanaAno] [varchar](255) NULL,
	[NumDia] [int] NULL,
	[NumDiaSemana] [int] NULL,
	[DescDiaSemana] [varchar](255) NULL,
	[FlgFinalSemana] [varchar](255) NULL
) ON [PRIMARY]
 '''

sqlDSTG_OiMasterDados_Tab02 = ''' 
use DSTG_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiSTG_Cidade')  
   DROP TABLE [OiMasterDados].[TOiSTG_Cidade]

CREATE TABLE [OiMasterDados].[TOiSTG_Cidade](
	[NumCidade] [int] NULL,
	[Cidade] [varchar](255) NULL,
	[Estado] [varchar](255) NULL,
	[Pais] [varchar](255) NULL,
	[RegiaoGlobo] [varchar](255) NULL
) ON [PRIMARY]
'''

sqlDSTG_OiMasterDados_Tab03 = ''' 
use DSTG_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiSTG_CidadeGeoLocalizacao')  
   DROP TABLE [OiMasterDados].[TOiSTG_CidadeGeoLocalizacao]
   
CREATE TABLE [OiMasterDados].[TOiSTG_CidadeGeoLocalizacao](
	[Localizacao] [varchar](MAX) NULL,
	[ValLatitude] [float] NULL,
	[ValLongitude] [float] NULL
) ON [PRIMARY]
'''

sqlDSTG_OiMasterDados_Tab04 = ''' 
use DSTG_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiSTG_CityTemperatureCsv')  
   DROP TABLE [OiMasterDados].[TOiSTG_CityTemperatureCsv]

CREATE TABLE [OiMasterDados].[TOiSTG_CityTemperatureCsv](
	[Region] [varchar](255) NULL,
	[Country] [varchar](255) NULL,
	[State] [varchar](255) NULL,
	[City] [varchar](255) NULL,
	[Month] [int] NULL,
	[Day] [int] NULL,
	[Year] [int] NULL,
	[AvgTemperature] [float] NULL
) ON [PRIMARY]
'''

sqlDSTG_OiMasterDados_Tab05 = ''' 
use DSTG_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiSTG_FatoTemperatura')  
   DROP TABLE [OiMasterDados].[TOiSTG_FatoTemperatura]

CREATE TABLE [OiMasterDados].[TOiSTG_FatoTemperatura](
	[NumData] [int] NULL,
	[NumDataOrigem] [int] NULL,
	[FlgFormDataCorreta] [varchar](255) NULL,
	[NumCidade] [int] NULL,
	[ValMedioTemperaturaC] [float] NULL
) ON [PRIMARY]
'''

try:
    cursorDSTG_Tabela.execute(sqlDSTG_OiMasterDados_Tab01)
    connDSTG.commit()
    print('Executado o script SQL para criação da tabela 01.')
except:
    print('Erro. Contactar desenvolvedor!')

try:
    cursorDSTG_Tabela.execute(sqlDSTG_OiMasterDados_Tab02)
    connDSTG.commit()
    print('Executado o script SQL para criação da tabela 02.')
except:
    print('Erro. Contactar desenvolvedor!')
    
try:
    cursorDSTG_Tabela.execute(sqlDSTG_OiMasterDados_Tab03)
    connDSTG.commit()
    print('Executado o script SQL para criação da tabela 03.')
except:
    print('Erro. Contactar desenvolvedor!')
    
try:
    cursorDSTG_Tabela.execute(sqlDSTG_OiMasterDados_Tab04)
    connDSTG.commit()
    print('Executado o script SQL para criação da tabela 04.')
except:
    print('Erro. Contactar desenvolvedor!')
    
try:
    cursorDSTG_Tabela.execute(sqlDSTG_OiMasterDados_Tab05)
    connDSTG.commit()
    print('Executado o script SQL para criação da tabela 05.')
except:
    print('Erro. Contactar desenvolvedor!')

Executado o script SQL para criação da tabela 01.
Executado o script SQL para criação da tabela 02.
Executado o script SQL para criação da tabela 03.
Executado o script SQL para criação da tabela 04.
Executado o script SQL para criação da tabela 05.

In [9]:
# criando as tabelas no esquema OiMasterDados para os banco de dados DSTG_OiMasterDados
cursorDDTM_Tabela = connDDTM.cursor()

sqlDDTM_OiMasterDados_Tab01 = ''' 
use DDTM_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiDIM_Calendario')  
   DROP TABLE [OiMasterDados].[TOiDIM_Calendario]
   
CREATE TABLE [OiMasterDados].[TOiDIM_Calendario](
	[CodSkData] [int] NOT NULL,
	[CodBkData] [date] NOT NULL,
	[NumAno] [int] NOT NULL,
	[DescAno] [varchar](60) NOT NULL,
	[NumSemestre] [int] NOT NULL,
	[DescSemestre] [varchar](60) NOT NULL,
	[NumTrimestre] [int] NOT NULL,
	[DescTrimestre] [varchar](60) NOT NULL,
	[NumMes] [int] NOT NULL,
	[DescMes] [varchar](60) NOT NULL,
	[NumSemanaAno] [int] NOT NULL,
	[DescSemanaAno] [varchar](60) NOT NULL,
	[NumDia] [int] NOT NULL,
	[NumDiaSemana] [int] NOT NULL,
	[DescDiaSemana] [varchar](60) NOT NULL,
	[FlgFinalSemana] [char](1) NOT NULL,
	[DescEstacaoBoreal] varchar(60) NULL,
	[DescEstacaoAustral] varchar(60) NULL
	CONSTRAINT PK_TOiDIM_Calendario PRIMARY KEY CLUSTERED ([CodSkData])
) ON [PRIMARY]
 '''

sqlDDTM_OiMasterDados_Tab02 = ''' 
use DDTM_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiDIM_Cidade')  
   DROP TABLE [OiMasterDados].[TOiDIM_Cidade]

CREATE TABLE [OiMasterDados].[TOiDIM_Cidade](
	CodSkCidade [int]				NOT NULL,
	[NomCidade] [varchar](200)		NOT NULL,
	[NomEstado] [varchar](80)		NOT NULL,
	[NomPais] [varchar](120)		NOT NULL,
	[NomRegiaoGlobo] [varchar](80)	NOT NULL,
	[ValLatitude] [float]			NULL,
	[ValLongitude] [float]			NULL,
	[FlgHemisferioNorte] char(1)    NULL
	CONSTRAINT PK_TOiDIM_Cidade PRIMARY KEY CLUSTERED (CodSkCidade)
) ON [PRIMARY]
'''

sqlDDTM_OiMasterDados_Tab03 = ''' 
use DDTM_OiMasterDados

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'OiMasterDados' AND name like 'TOiFAT_Temperatura')  
   DROP TABLE [OiMasterDados].[TOiFAT_Temperatura]
   
CREATE TABLE [OiMasterDados].[TOiFAT_Temperatura](
	[CodSkData] [int] NOT NULL,
	[CodSkCidade] [int] NOT NULL,
	[ValMedioTemperaturaC] [float] NOT NULL
	,CONSTRAINT FK_Temperatura_Calendario FOREIGN KEY (CodSkData)
        REFERENCES [OiMasterDados].[TOiDIM_Calendario] (CodSkData)
        ON DELETE CASCADE
        ON UPDATE CASCADE
	,CONSTRAINT FK_Temperatura_Cidade FOREIGN KEY (CodSkCidade)
        REFERENCES [OiMasterDados].[TOiDIM_Cidade] (CodSkCidade)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON [PRIMARY]
'''

try:
    cursorDDTM_Tabela.execute(sqlDDTM_OiMasterDados_Tab01)
    connDDTM.commit()
    print('Executado o script SQL para criação da tabela 01.')
except:
    print('Erro. Contactar desenvolvedor!')

try:
    cursorDDTM_Tabela.execute(sqlDDTM_OiMasterDados_Tab02)
    connDDTM.commit()
    print('Executado o script SQL para criação da tabela 02.')
except:
    print('Erro. Contactar desenvolvedor!')
    
try:
    cursorDDTM_Tabela.execute(sqlDDTM_OiMasterDados_Tab03)
    connDDTM.commit()
    print('Executado o script SQL para criação da tabela 03.')
except:
    print('Erro. Contactar desenvolvedor!')

Executado o script SQL para criação da tabela 01.
Executado o script SQL para criação da tabela 02.
Executado o script SQL para criação da tabela 03.

## FIM